### ISSUE TITLE
"conda env create" crashes for MacOS + python 3.10, 3.11

### ISSUE THREAD

**Issue by giardiaspace** [spacetelescope/stenv#103]
When I try to create the stenv environment, conda crashes.

**Steps that can reproduce the error:**
1. `curl -L "https://github.com/spacetelescope/stenv/releases/download/2023.04.14/stenv-macOS-py3.11-2023.04.05.yaml" -o ~/.conda/stenv-macOS-py3.11-2023.04.05.yaml`
2. `conda env create --file ~/.conda/stenv-macOS-py3.11-2023.04.05.yaml --name stenv`
3. Here is a partial error output from the resulting crash:

```
Failed to build opencv-python
  Building wheel for opencv-python (pyproject.toml) did not run successfully.
        CMake's 'find_host_package(PythonInterp 2.7)' found wrong Python version:
      
        PYTHON_EXECUTABLE=/Users/mikewong/opt/anaconda3/envs/stenv/bin/python
      
        PYTHON_VERSION_STRING=3.11.3
      
        Consider providing the 'PYTHON2_EXECUTABLE' variable via CMake command line
        or environment variables
      
      [  0%] Built target opencv_dnn_plugins
      [  0%] Built target opencv_highgui_plugins
      [  0%] Building ASM_NASM object 3rdparty/libjpeg-turbo/src/simd/CMakeFiles/jsimd.dir/x86_64/jsimdcpu.asm.o
      nasm: error: unable to find utility "nasm", not a developer tool or in PATH
      make[2]: *** [3rdparty/libjpeg-turbo/src/simd/CMakeFiles/jsimd.dir/x86_64/jsimdcpu.asm.o] Error 72
      make[1]: *** [3rdparty/libjpeg-turbo/src/simd/CMakeFiles/jsimd.dir/all] Error 2
      make: *** [all] Error 2
      Traceback (most recent call last):

      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for opencv-python
  ERROR: Could not build wheels for opencv-python, which is required to install pyproject.toml-based projects
```

Hardware/software info if relevant:
      Model Name: Mac Pro
      Model Identifier: MacPro5,1
      Processor Name: Quad-Core Intel Xeon
      System Version: macOS 10.14.6 (18G9323)
      Kernel Version: Darwin 18.7.0
          conda version : 22.9.0

Could this relate to opencv-python not supporting builds in Mac OS 10.x any more? See "Backward compatibility" [here](https://pypi.org/project/opencv-python/) and this [issue thread](https://github.com/opencv/opencv-python/issues/657).

I tried to insteall with python 3.10 instead of 3.11, and set opencv-python==4.6.0.66 in the yaml, but pip again crashed trying to install opencv-python. 

Is there any way you could modify dependencies to use opencv-python-headless instead? I ask because this command works fine:

``conda install opencv-python-headless=4.7.0.72 -n stenv -c fastai``

**Comment by zacharyburnett** [comment]
We've tested `opencv-python-headless` in the step code, and it should work well according to the tests. You should see this change in the next set of releases of `stcal` and `jwst`

**Comment by giardiaspace** [comment]
Hi Zach,

Thanks for looking into that. I kept running into further 
problems, so I am finally starting to accept that my 2010 
computer running macos 10.14 is not going to be able to keep 
going. 

But I was able to easily install stenv (with the existing YAML) 
on my laptop running macos 14. I just didn't want my laptop to be 
tied up in processing batches. 

Thanks again for your responsiveness. 



On Fri, 28 Apr 2023, Zach Burnett wrote:

- We've tested `opencv-python-headless` in the step code, and it should work well according to the tests. You should see this change in the next set of releases of `stcal` and `jwst`
- 
- -- 
- Reply to this email directly or view it on GitHub:
- https://github.com/spacetelescope/stenv/issues/103#issuecomment-1527636442
- You are receiving this because you authored the thread.
- 
- Message ID: ***@***.***>

................................mike wong...................
                                center for integrative planetary science
                                university of california
                                berkeley CA 94720-3411

                                astro.berkeley.edu/~mikewong
                                campbell hall 215 (office)
                                510-207-2236 (cell)
