### ISSUE TITLE
Current release provides files from the previous release (04.14 <-> 04.05)

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/stenv#106]
![Screenshot_20230531_104752](https://github.com/spacetelescope/stenv/assets/490981/4fde9239-509e-4144-b828-d9e9e82cebe5)

@zacharyburnett I diffed the 04.05 release with 04.14's "04.05" files and there was no difference. Did something go wrong here, or is 04.14 a re-release of 04.05 under a different name?

**Comment by zacharyburnett** [comment]
ah, good catch, it looks like the version number wasn't parsed correctly:
https://github.com/spacetelescope/stenv/actions/runs/4698978240/jobs/8335136566#step:4:36
```
Run mtkennerly/dunamai-action@v1
Run python -m action
Running command: pip install dunamai
Running command: dunamai from any --pattern "(?P<base>\d+\.\d+\.\d+)"
Dynamic version: 2023.04.05
```

I'll look into this, and see if I can upload the correct files / make another release with a fix

**Comment by jhunkeler** [comment]
Oops! :sweat_smile: 
Sounds good, I'll keep an eye out for the updated/fixed release.

**Comment by zacharyburnett** [comment]
ah I see now, it's because both tags are on the same commit, so it got confused:
<img width="182" alt="image" src="https://github.com/spacetelescope/stenv/assets/16024299/f7c57ce7-27e0-487a-af22-125b9a24c5be">

I made another release on the same commit to retrigger the environment after releasing some packages; I'll keep this in mind next time

**Comment by jhunkeler** [comment]
Hey -- looks like the build failed https://github.com/spacetelescope/stenv/actions/runs/5134878703 and a release object was generated anyway https://github.com/spacetelescope/stenv/releases/tag/2023.05.31

**Comment by zacharyburnett** [comment]
It looks like this issue is resolved by not releasing twice on the same commit; I will close this ticket
