### ISSUE TITLE
`<error>` happens upon doing conda env create --name stenv --file stenv-macOS-ARM64-py3.x-2024.02.05.yaml 

### ISSUE THREAD

**Issue by starlinker86** [spacetelescope/stenv#151]
When I do 
conda env create --name stenv --file stenv-macOS-ARM64-py3.x-2024.02.05.yaml
, something bad happens and / or I get the error `<error>`.

Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package imagecodecs-2024.1.1-py310h5cce2fa_0 requires c-blosc2 >=2.12.0,<2.13.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ c-blosc2 2.13.1**  is requested and can be installed;
├─ imagecodecs 2024.1.1**  is installable with the potential options
│  ├─ imagecodecs 2024.1.1 would require
│  │  └─ libpng >=1.6.43,<1.7.0a0 , which can be installed;
│  └─ imagecodecs 2024.1.1 would require
│     └─ c-blosc2 >=2.12.0,<2.13.0a0 , which conflicts with any installable versions previously reported;
└─ libpng 1.6.42**  is not installable because it conflicts with any installable versions previously reported.

**Comment by starlinker86** [comment]
Thank you very much！
The command works now!

The version of macOS is: sonoma 14.4.1 (23E224)
Thanks again！

From: Zach Burnett ***@***.***>
Date: Wednesday, May 1, 2024 at 15:51
To: spacetelescope/stenv ***@***.***>
Cc: star ***@***.***>, Author ***@***.***>
Subject: Re: [spacetelescope/stenv] `<error>` happens upon doing conda env create --name stenv --file stenv-macOS-ARM64-py3.x-2024.02.05.yaml (Issue #151)

Good morning! I apologize for the delay in responding to this. Could you let me know what version of macOS you're running (🍎 -> About This Mac)?

Also, what happens when you try with the latest release?

conda env create --name stenv --file https://github.com/spacetelescope/stenv/releases/download/2024.04.29/stenv-macOS-ARM64-py3.11-2024.04.29.yaml

If that doesn't work, do you get the same error if you try building the environment directly from environment.yml?

conda env create --name stenv --file https://raw.githubusercontent.com/spacetelescope/stenv/main/environment.yaml

**Comment by zacharyburnett** [comment]
Fantastic to hear! I'm glad I was able to help
