### ISSUE TITLE
Does this support IRAF?

### ISSUE THREAD

**Issue by aragilar** [spacetelescope/stenv#73]
Looking at the warnings on the astroconda docs about it disappearing and being pointed at this, I was trying to work out what was changing. It looks to me like the main change is dropping the IRAF ecosystem. Is the removal of IRAF intentional (not that I'd blame you for dropping it), or is IRAF support something you haven't got around to? If IRAF is being dropped, then it would seem like a good idea to flag this on the astroconda docs, so that users are aware they need to look elsewhere for IRAF support.

**Comment by nden** [comment]
@aragilar STScI dropped support for IRAF in 2019. The current conda channel which includes iraf is maintained mostly for external use. It will stay for the time being available though we are not really supporting it and it works with Python 2.7 only which isn't supported either.

The main change concerns the way we distribute STScI software (the astroconda-contrib channel). We've stopped updating it and moved our distribution to stenv which works with all modern versions of Python and numpy. I believe there's a community maintained iraf distribution but I'll need to look for it. I can find more information if you need it and post here.

**Comment by aragilar** [comment]
That's cool. https://github.com/iraf-community is the github org you're thinking of. It was mainly trying to work out what to recommend people (especially novice users) use for getting IRAF (as the general recommendation here in Australia is to use astroconda for getting IRAF for any telescope/instrument (should be was, but I don't think people have realised yet that astroconda is going away)).
